
name: Build and test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'

      - name: Prepare CUDA Toolkit
        run: |
          export CPATH="$CUDA_PATH/include:$CPATH"
          export CUDA_HOME="$CUDA_PATH"
          export PATH=$PATH:"$CUDA_PATH"
          export PATH=$PATH:"$CUDA_PATH/bin"
          export PATH=$PATH:"$CUDA_PATH/include"
          export LD_LIBRARY_PATH="$CUDA_PATH/lib:$LD_LIBRARY_PATH"
          export LD_LIBRARY_PATH="$CUDA_PATH/lib64:$LD_LIBRARY_PATH"

      - name: Check CUDA version
        run: nvcc -V

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install cucounter
        run: pip install .

      - name: Run tests
        run: |
          ./run_tests
        
